# Use an official base image
FROM ubuntu:latest

# Set the working directory
WORKDIR /app

# Copy the local script files to the container
COPY . /app

# Make the scripts executable
RUN chmod +x *.sh

